# Generated by Django 4.1 on 2022-10-30 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocerystore', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exito',
            name='quantity',
        ),
        migrations.AddField(
            model_name='marketday',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='marketday',
            name='total_purchased',
            field=models.IntegerField(default=0),
        ),
    ]
