# Generated by Django 4.1 on 2022-10-30 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocerystore', '0003_alter_exito_date_price_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exito',
            name='date_price_updated',
            field=models.DateTimeField(default='2022-10-29 14:42:00', verbose_name='date published'),
        ),
    ]
