# Generated by Django 4.1 on 2022-10-31 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocerystore', '0007_alter_exito_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exito',
            name='group',
            field=models.CharField(choices=[('_FOOD_', 'Food'), ('_CLEANING_', 'Cleaning'), ('_VEGETABLES_', 'Vegetables')], max_length=12),
        ),
    ]
