# Generated by Django 4.1 on 2022-10-31 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grocerystore', '0009_alter_exito_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exito',
            name='group',
        ),
    ]
