# Generated by Django 4.1 on 2022-10-31 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocerystore', '0010_remove_exito_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='exito',
            name='element_group',
            field=models.CharField(choices=[('F', 'FOOD'), ('C', 'CLEANING'), ('V', 'VEGETABLES')], default='F', max_length=1),
        ),
    ]
