# Generated by Django 4.1 on 2022-10-31 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocerystore', '0011_exito_element_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exito',
            name='element_group',
            field=models.CharField(choices=[('FOOD', 'FOOD'), ('CLEANING', 'CLEANING'), ('VEGETABLES', 'VEGETABLES')], default='FOOD', max_length=10),
        ),
    ]
