# Generated by Django 4.1 on 2022-10-31 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocerystore', '0012_alter_exito_element_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='exito',
            name='exito_code',
            field=models.CharField(default=0, max_length=20, unique=True),
        ),
    ]
