# Generated by Django 4.1 on 2022-10-31 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocerystore', '0014_alter_exito_exito_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exito',
            name='bar_code',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='exito',
            name='exito_code',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
