# Generated by Django 4.1 on 2022-10-31 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocerystore', '0015_alter_exito_bar_code_alter_exito_exito_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exito',
            name='bar_code',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
