# Generated by Django 4.1 on 2022-10-31 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocerystore', '0016_alter_exito_bar_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exito',
            name='bar_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
